openapi: 3.0.1
info:
  title: POC API Gateway OpenAPI
  description: API Gateway demonstration using OpenAPI Specification
  version: 1.0.0

tags:
  - name: Endpoints
    description: Endpoints for the user to interact with

security:
  - BearerAuth: []

paths:
  /submit:
    post:
      summary: Post name, age and height of user
      tags:
        - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userdata'
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${post_data_invoke_arn}"
      responses:
        '201':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/postresponse'
        '400':
          description: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errormessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalmessage'
  
  /retrieve/{uuid}:
    get:
      summary: Get name, age and height of existing UUID
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      tags:
          - Endpoints
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${retrieve_data_invoke_arn}"
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/userdata'
        '403':
          description: Unauthorised access (request sent during data processing)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorisedmessage'
        '404':
          description: UUID data missing
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/missingmessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalmessage'

  /update/{uuid}:
    post:
      summary: Update name, age and height of existing UUID
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      tags:
          - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userdata'
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${update_data_invoke_arn}"
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/updateresponse'
        '400':
          description: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errormessage'
        '403':
          description: Unauthorised access (request sent during data processing)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorisedmessage'
        '404':
          description: UUID data missing
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/missingmessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalmessage'

  /delete/{uuid}:
    delete:
      summary: Delete name, age and height of existing UUID
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      tags:
          - Endpoints
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${delete_data_invoke_arn}"
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/deleteresponse'
        '403':
          description: Unauthorised access (request sent during data processing)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorisedmessage'
        '404':
          description: UUID data missing
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/missingmessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalmessage'
      
components:
  schemas:
    userdata:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          minimum: 0
        height:
          type: number
          minimum: 0
    postresponse:
      type: object
      properties:
        message:
          type: string
          example: 'Data successfully uploaded!'
        uuid:
          type: string
          example: 'd8a7567b-98fb-4363-a3d8-ed0296ab2936'
    updateresponse:
      type: object
      properties:
        message:
          type: string
          example: 'Data successfully updated!'
    deleteresponse:
      type: object
      properties:
        message:
          type: string
          example: 'Data successfully deleted!'
    errormessage:
      type: object
      properties:
        message:
          type: string
          example: "Error message."
    unauthorisedmessage:
      type: object
      properties:
        message:
          type: string
          example: "Unauthorised message."
    missingmessage:
      type: object
      properties:
        message:
          type: string
          example: "Missing data message."
    internalmessage:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error message."

  securitySchemes:
    BearerAuth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: token
        authorizerUri: "${authorise_invoke_arn}"
        identitySource: method.request.header.Authorization
        authorizerResultTtlInSeconds: 0